---
dist: xenial
sudo: false

addons:
  apt:
    packages:
      - python3-pip

install:
- pip3 install linkstatus
script:
- linkstatus --recursive --timeout 10 --retry 5 tests 2018 2019
after_failure:
- git diff
